#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# This script is used to configure the nssdc machine
#
# Currently tested on Zentyal 7.1

setup() {
  if ! internal_dependencies; then
    echo "ERROR: Failed to setup internal dependencies"
    return 1
  fi

  # Install necessary packages
  if ! pkg_install "sshpass"; then
    logError "Failed to install sshpass"
    return 1
  fi

  # Setup AD replication
  if ! zl_configure_replication "${PDC_USER}" "${PDC_PASSWORD}"; then
    logError "Failed to configure replication"
    return 1
  fi

  logInfo "Setup complete!"

  return 0
}

install_encryption() {
  # Install and configure encryption tools
  if ! sops_install; then
    logError "Failed to install sops"
    return 1
  fi
  if ! age_install; then
    logError "Failed to install age"
    return 1
  fi

  if [[ -z "${AGE_KEY}" ]]; then
    logError "AGE_KEY is not set."
    return 1
  elif ! age_configure "${AGE_KEY}"; then
    logError "Failed to generate age key"
    return 1
  fi

  return 0
}

internal_dependencies() {
  logInfo "Setting up internal dependencies"

  DOWNLOAD_DIR="${DC_ROOT}/.downloads"
  BIN_DIR="${DC_ROOT}/bin"
  export DOWNLOAD_DIR
  export BIN_DIR

  # shellcheck disable=SC1090
  if ! source "${SETUP_DIR}/src/zentyal.sh"; then
    logError "Failed to load zentyal.sh"
    return 1
  elif ! source "${SETUP_DIR}/src/pkg.sh"; then
    logError "Failed to load pkg.sh"
    return 1
  elif ! source "${SETUP_DIR}/src/sops.sh"; then
    logError "Failed to load sops.sh"
    return 1
  elif ! source "${SETUP_DIR}/src/age.sh"; then
    logError "Failed to load age.sh"
    return 1
  elif ! install_encryption; then
    logError "Failed to setup encryption tools"
    return 1
  fi

  # Install config.sh
  if [[ ! -f "${PREFIX}/lib/config.sh" ]]; then
    if ! sudo bpkg install -g jeremfg/config.sh; then
      logError "Failed to install config.sh"
      return 1
    else
      logInfo "config.sh installed successfully"
    fi
  fi

  # Source Configuration
  # shellcheck disable=SC1090
  if ! source "${PREFIX}/lib/config.sh"; then
    logError "Failed to import config.sh"
    return 1
  elif ! config_load "${DC_ROOT}/.config/pdc.env"; then
    logError "Failed to load PDC configuration"
    return 1
  elif [[ -z "${PDC_USER}" ]]; then
    logError "PDC_USER is not set in configuration"
    return 1
  elif [[ -z "${PDC_PASSWORD}" ]]; then
    logError "PDC_PASSWORD is not set in configuration"
    return 1
  else
    logInfo "Internal dependencies loaded successfully"
  fi

  return 0
}

external_dependencies() {
  SETUP_DIR="${DC_ROOT}/external/setup"

  # Configure logger
  export LOG_CONSOLE=1
  export LOG_LEVEL=0

  PREFIX="/usr/local"
  export PREFIX

  # Install BPKG
  if ! command -v bpkg >/dev/null 2>&1; then
    echo "WARN: bpkg is not installed. Please install it first."
    if ! command -v wget >/dev/null 2>&1; then
      echo "ERROR: wget is not installed. Please install it first."
      return 1
    elif ! wget -qO- "${BPKG_DL_URL}" | sudo bash; then
      echo "ERROR: Failed to install bpkg"
      return 1
    else
      echo "bpkg installed successfully"
    fi
  fi

  # Install slf4.sh
  if [[ ! -f "${PREFIX}/lib/slf4.sh" ]]; then
    if ! sudo bpkg install -g jeremfg/slf4.sh; then
      echo "Failed to install slf4.sh"
      return 1
    else
      echo "slf4.sh installed successfully"
    fi
  fi

  # Load the libraries
  # shellcheck disable=SC1090
  if ! source "${PREFIX}/lib/slf4.sh"; then
    echo "Failed to import slf4.sh"
    exit 1
  fi

  # Install Semver
  if ! command -v semver >/dev/null 2>&1; then
    if ! sudo bpkg install -g jeremfg/semver.sh; then
      logError "Failed to install semver"
      return 1
    else
      logInfo "semver installed successfully"
    fi
  fi

  return 0
}

# Undefined variables
if [[ -z "${PDC_USER}" ]]; then PDC_USER=""; fi
if [[ -z "${PDC_PASSWORD}" ]]; then PDC_PASSWORD=""; fi

# Constants
BPKG_DL_URL="https://get.bpkg.sh"
AGE_KEY="homeinfra_demers"

###########################
###### Startup logic ######
###########################

# Get root directory of the project
# https://stackoverflow.com/a/246128
DC_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${DC_SOURCE}" ]]; do # resolve $DC_SOURCE until the file is no longer a symlink
  DC_ROOT=$(cd -P "$(dirname "${DC_SOURCE}")" >/dev/null 2>&1 && pwd)
  DC_SOURCE=$(readlink "${DC_SOURCE}")
  [[ ${DC_SOURCE} != /* ]] && DC_SOURCE=${DC_ROOT}/${DC_SOURCE} # if $DC_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DC_ROOT=$(cd -P "$(dirname "${DC_SOURCE}")" >/dev/null 2>&1 && pwd)
DC_ROOT=$(realpath "${DC_ROOT}/..")

if ! external_dependencies; then
  echo "ERROR: External dependencies are not met"
  exit 1
fi

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  setup "${@}"
  exit $?
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  setup "${@}"
  exit $?
fi
